apiVersion: v1
kind: Service
metadata:
  name: jenkins-aks-demo-service
spec:
  type: LoadBalancer
  selector:
    app: jenkins-aks-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
